# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c850389204f0865be57c2f639a59c0e5299ac5828e63ecbf64352c780394f204212b39e185c7862eeeff9420eb4b379b76f0e5194c0d0619a48a70e23798150

test:
  secret_key_base: 986c8b819dd126b9d5d224a40d091f299a31917ae27bf9f7a3dfd26bcfe2ed14aa178dd7be101102788784ebbeabf5de096dc614ede9d47bc3aefc3ab56a6ca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
